# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Conversor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 175)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_igualdade = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(10)
        self.lbl_igualdade.setFont(font)
        self.lbl_igualdade.setObjectName("lbl_igualdade")
        self.gridLayout.addWidget(self.lbl_igualdade, 1, 1, 1, 1)
        self.frm_saida = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.frm_saida.setFont(font)
        self.frm_saida.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frm_saida.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_saida.setObjectName("frm_saida")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frm_saida)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cmb_saida = QtWidgets.QComboBox(self.frm_saida)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.cmb_saida.setFont(font)
        self.cmb_saida.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(46, 52, 54);")
        self.cmb_saida.setObjectName("cmb_saida")
        self.gridLayout_3.addWidget(self.cmb_saida, 1, 0, 1, 1)
        self.txt_saida = QtWidgets.QLineEdit(self.frm_saida)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.txt_saida.setFont(font)
        self.txt_saida.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txt_saida.setReadOnly(True)
        self.txt_saida.setObjectName("txt_saida")
        self.gridLayout_3.addWidget(self.txt_saida, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frm_saida, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_titulo = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setStyleSheet("")
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lbl_titulo)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 3)
        self.frm_entrada = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.frm_entrada.setFont(font)
        self.frm_entrada.setStyleSheet("")
        self.frm_entrada.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frm_entrada.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_entrada.setObjectName("frm_entrada")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frm_entrada)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmb_entrada = QtWidgets.QComboBox(self.frm_entrada)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.cmb_entrada.setFont(font)
        self.cmb_entrada.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(46, 52, 54);")
        self.cmb_entrada.setObjectName("cmb_entrada")
        self.gridLayout_2.addWidget(self.cmb_entrada, 1, 0, 1, 1)
        self.txt_entrada = QtWidgets.QLineEdit(self.frm_entrada)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.txt_entrada.setFont(font)
        self.txt_entrada.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txt_entrada.setObjectName("txt_entrada")
        self.gridLayout_2.addWidget(self.txt_entrada, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frm_entrada, 1, 0, 1, 1)
        self.btn_reiniciar = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.btn_reiniciar.setFont(font)
        self.btn_reiniciar.setDefault(True)
        self.btn_reiniciar.setObjectName("btn_reiniciar")
        self.gridLayout.addWidget(self.btn_reiniciar, 2, 2, 1, 1)
        self.btn_converter = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(10)
        self.btn_converter.setFont(font)
        self.btn_converter.setDefault(True)
        self.btn_converter.setFlat(False)
        self.btn_converter.setObjectName("btn_converter")
        self.gridLayout.addWidget(self.btn_converter, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Conversor"))
        self.lbl_igualdade.setText(_translate("Form", "="))
        self.lbl_titulo.setText(_translate("Form", "> > > Conversor de temperaturas < < <"))
        self.btn_reiniciar.setText(_translate("Form", "Reiniciar"))
        self.btn_converter.setText(_translate("Form", "Converter"))

